# 1. This yaml file was based on the specific computer configuration UniSpec was trained, 
#    and may need to be adjusted for your real condition.
# 2. The following input files can be ontained from the UniSpec Zenoda download 
#	folder "Streamlined_inputdatasets.zip", see "Readme_Streamlined_inputdatasets.txt".

train:
   labels: ./input_data/labels/train_labels.txt
   pos: ./input_data/txt_pos/fpostrain.txt
   data: ./input_data/datasets/train.txt
val:
   labels: ./input_data/labels/val_labels.txt
   pos: ./input_data/txt_pos/fposval.txt
   data: ./input_data/datasets/val.txt
test:
   labels: ./input_data/labels/test_labels.txt
   pos: ./input_data/txt_pos/fpostest.txt
   data: ./input_data/datasets/test.txt

config:
weights:
restart:
transfer:

model_config:
   embedsz: 256
   blocks: 9
   head:
      - 16
      - 16
      - 64
   units: None
   filtlast: 512
   CEembed: True
   learn_ffn_embed: False

root_int: 2
lr: 3e-4
epochs: 20
steps: 10000
batch_size: 100
lr_decay_start: 20
lr_decay_rate: 0.85
svwts: all
